Enhavo\Bundle\ShopBundle\Entity\ProductOption:
    type: entity
    table: shop_product_option

    fields:
        name:
            type: string
            nullable: true

    lifecycleCallbacks: {  }
