Enhavo\Bundle\ShopBundle\Entity\ProductOption:
    type: entity
    table: shop_product_option

    manyToOne:
        route:
            cascade: ['persist', 'refresh', 'remove']
            targetEntity: Enhavo\Bundle\RoutingBundle\Model\RouteInterface
            orphanRemoval: true

    lifecycleCallbacks: {  }
