Enhavo\Bundle\ShopBundle\Entity\ProductOption:
    type: entity
    table: shop_product_option

    properties:
        position:
            type: integer
            nullable: true

    lifecycleCallbacks: {  }
